Blog/Controllers/AdminBlogPostController.cs
using Blog.Models.Domain;
using Blog.Models.ViewModels;
using Blog.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Blog.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminBlogPostController : Controller
    {
        private readonly IBlogPostRepository _blogPostRepository;
        private readonly ITagRepository _tagRepository;

        public AdminBlogPostController(IBlogPostRepository blogPostRepository, ITagRepository tagRepository)
        {
            _blogPostRepository = blogPostRepository;
            _tagRepository = tagRepository;
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var tags = await _tagRepository.GetAllAsync();
            var model = new AddBlogPostRequest
            {
                Tags = tags.Select(x => new SelectListItem { Text = x.Name,Value = x.Id.ToString() })
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddBlogPostRequest addBlogPostRequest)
        {
            // map view mode to domain model
            var blogPost = new BlogPost
            {
                Heading = addBlogPostRequest.Heading,
                PageTitle = addBlogPostRequest.PageTitle,
                Content = addBlogPostRequest.Content,
                ShortDescription = addBlogPostRequest.ShortDescription,
                FeaturedImageUrl = addBlogPostRequest.FeaturedImageUrl,
                UrlHandle = addBlogPostRequest.UrlHandle,
                PublishedDate = addBlogPostRequest.PublishedDate,
                Author = addBlogPostRequest.Author,
                Visible = addBlogPostRequest.Visible
            };

            var selectedTags = new List<Tag>();
            // map tags from selectedTags 
            // we are getting ids of tags so we need to get the data from database using selectedTags Id
            foreach (var selectedTagId in addBlogPostRequest.SelectedTags)
            {
                var selecteTagIdAsGuid = Guid.Parse(selectedTagId);
                var existingTag = await _tagRepository.GetAsync(selecteTagIdAsGuid);

                if(existingTag != null)
                {
                   selectedTags.Add(existingTag);
                }

            }
            // mapping tags to domain model
            blogPost.Tags = selectedTags;

            await _blogPostRepository.AddAsync(blogPost);
            return RedirectToAction("Add");
        }

        [HttpGet]
        public async Task<IActionResult> List()
        {
            // call the repository
            var blogPost = await _blogPostRepository.GetAllAsync();
            return View(blogPost);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            // retrive the result from repository
            var existingBlogPost = await _blogPostRepository.GetAsync(id);

            // get all tags
            var tagsDomainModel = await _tagRepository.GetAllAsync();

            if (existingBlogPost != null)
            {
                // map domain model into view model
                var model = new EditBlogPostRequest
                {
                    Id = existingBlogPost.Id,
                    Heading = existingBlogPost.Heading,
                    PageTitle = existingBlogPost.PageTitle,
                    PublishedDate = existingBlogPost.PublishedDate,
                    Content = existingBlogPost.Content,
                    Author = existingBlogPost.Author,
                    ShortDescription = existingBlogPost.ShortDescription,
                    FeaturedImageUrl = existingBlogPost.FeaturedImageUrl,
                    UrlHandle = existingBlogPost.UrlHandle,
                    Visible = existingBlogPost.Visible,
                    Tags = tagsDomainModel.Select(x => new SelectListItem
                    {
                        Text = x.Name,
                        Value = x.Id.ToString(),
                    }),
                    SelectedTags = existingBlogPost.Tags.Select(x => x.Id.ToString()).ToArray(),
                };
                return View(model);
            }
            return View(null);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditBlogPostRequest editBlogPostRequest)
        {
            // map blog post to doamin model
            var blogPostDomainModel = new BlogPost
            {
                Id = editBlogPostRequest.Id,
                Heading = editBlogPostRequest.Heading,
                Content = editBlogPostRequest.Content,
                PageTitle = editBlogPostRequest.PageTitle,
                Author = editBlogPostRequest.Author,
                ShortDescription = editBlogPostRequest.ShortDescription,
                FeaturedImageUrl = editBlogPostRequest.FeaturedImageUrl,
                PublishedDate = editBlogPostRequest.PublishedDate,
                UrlHandle = editBlogPostRequest.UrlHandle,
                Visible = editBlogPostRequest.Visible,
            };

            // map tags to domain model
            var selectedTags = new List<Tag>();
            foreach (var selectedTag in editBlogPostRequest.SelectedTags)
            {
                if(Guid.TryParse(selectedTag, out var tag))
                {
                    var foundTag = await _tagRepository.GetAsync(tag);
                    if (foundTag != null)
                    {
                        selectedTags.Add(foundTag);
                    }
                }
            }

            blogPostDomainModel.Tags = selectedTags;

            // submit edited information to the repository
            var updatedBlog = await _blogPostRepository.UpdateAsync(blogPostDomainModel);

            if(updatedBlog != null)
            {
                // show success notification
                return RedirectToAction("List");
            }
                // show error notification
                return RedirectToAction("Edit");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(EditBlogPostRequest editBlogPostRequest)
        {
            var deleteBlogPost = await _blogPostRepository.DeleteAsync(editBlogPostRequest.Id);

            if (deleteBlogPost != null)
            {
                // Show success notification
                return RedirectToAction("List");
            }
            else
            {
                // show error notification
                return RedirectToAction("Edit");
            }
        }
    }
}

Blog/Controllers/AdminTagsController.cs
using Blog.Models.Domain;
using Blog.Models.ViewModels;
using Blog.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Blog.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminTagsController : Controller
    {
        private readonly ITagRepository _tagRepository;

        public AdminTagsController(ITagRepository tagRepository)
        {
            _tagRepository = tagRepository;
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ActionName("Add")]
        public async Task<IActionResult> Add(AddTagRequest addTagRequest)
        {
            ValidateAddTagRequest(addTagRequest);
            if (!ModelState.IsValid)
            {
                return View();
            }
            // comming tag is of type view model, map it to domain model before sends to DB
            var tag = new Tag
            {
                Name = addTagRequest.Name,
                DisplayName = addTagRequest.DisplayName,
            };

            await _tagRepository.AddAsync(tag);
            return RedirectToAction("List");
        }

        [HttpGet]
        [ActionName("List")]
        public async Task<IActionResult> List()
        {
            var tag = await _tagRepository.GetAllAsync();
            return View(tag);
        }

        [HttpGet]
        [ActionName("Edit")]
        // input parameter has to match with the route parameter => id, form list.cshtml
        public async Task<IActionResult> Edit(Guid id)
        {
            var tag = await _tagRepository.GetAsync(id);

            if(tag != null) 
            {
                var existingTag = new EditTagRequest
                {
                    Id= tag.Id,
                    Name = tag.Name,
                    DisplayName = tag.DisplayName,
                };
                return View(existingTag);
            }
            return View(null);
        }

        [HttpPost]
        // this method is used to update the data into DB in a edit action
        public async Task<IActionResult> Edit(EditTagRequest editTagRequest)
        {
            var tag = new Tag
            {
                Id = editTagRequest.Id,
                Name = editTagRequest.Name,
                DisplayName = editTagRequest.DisplayName,
            };

            var updatedTag = await _tagRepository.UpdateAsync(tag);

            if(updatedTag != null)
            {
                // show sucess notification
            }
            else
            {
                // show error notifiation
            }

            // if tag was not found we will redirect to the Edit View - it is taking parameter of id, 
            // so with object format we can send the Id to the edit method 

            // show error notification
            return RedirectToAction("Edit", new { id = editTagRequest.Id });        
        }

        [HttpPost]
        public async Task<IActionResult> Delete(EditTagRequest editTagRequest)
        {
            var deletedTag = await _tagRepository.GetAsync(editTagRequest.Id);

            if(deletedTag != null)
            {
                // show sucess notification
                return RedirectToAction("List");
            }
            return RedirectToAction("Edit", new { id = editTagRequest.Id });
        }
        
        private void ValidateAddTagRequest(AddTagRequest addTagRequest)
        {
            if(addTagRequest.Name is not null && addTagRequest.DisplayName is not null)
            {
                if(addTagRequest.Name == addTagRequest.DisplayName)
                {
                    ModelState.AddModelError("DisplayName", "Name can not be same as display name");
                }
            }
        }
    }
}

Blog/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> signInManger

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Blog</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Blog.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">

    <link href='https://cdn.jsdelivr.net/npm/froala-editor@latest/css/froala_editor.pkgd.min.css' rel='stylesheet' type='text/css' />

    <script type='text/javascript' src='https://cdn.jsdelivr.net/npm/froala-editor@latest/js/froala_editor.pkgd.min.js'></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Blog</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if(signInManger.IsSignedIn(User) && User.IsInRole("Admin"))    
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="AdminTags" asp-action="Add">Add Tag</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="AdminTags" asp-action="List">Show Tags</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="AdminBlogPost" asp-action="Add">Add Blog Post</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="AdminBlogPost" asp-action="List">All Blog Post</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="AdminUser" asp-action="List">All Users</a>
                            </li>
                        }
                    </ul>

                    <div class="d-flex align-items-center">

                        @if (signInManger.IsSignedIn(User))
                        {
                            <div class="me-3 text-light">
                                @User?.Identity?.Name
                            </div>

                            <a class="btn me-3 bg-light text-dark"
                           asp-area="" asp-controller="Account" asp-action="Logout">
                                Log Out
                            </a>
                        }
                        else
                        {

                            <a class="btn me-3 bg-light text-dark"
                           asp-area="" asp-controller="Account" asp-action="Login">
                                Login
                            </a>

                            <a class="btn me-3 bg-light text-dark"
                           asp-area="" asp-controller="Account" asp-action="Register">
                                Register
                            </a>
                        }
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div>
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Blog - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>